### ISSUE TITLE
Better commands system

### ISSUE THREAD

**Issue by kacperduras** [meleride/Paper#4]
* **I'm submitting a ...**
  - [x] feature request

* **What is the current behavior?**

Command registration, which depends a CommandExecutor interface.

* **If the issue isn't a support request, what is the expected behavior?**

I want to create an external library, based on annotations (inspiration: aikar/commands), with command arguments and i18n support. 

* **If the issue is a feature request, what is the motivation for add the behavior?**

Because recently system isn' t dynamic and comfortable, we must have a better solution for it.

**Comment by IceMeltt** [comment]
Hmm, how about adding commands just to the commandmaps in the registering process? 

This method will remove the requirement of adding every command to the plugin.yml file.

**Comment by kacperduras** [comment]
@IceMeltt This is my assumption, but if someone has a different idea, I'm waiting for feedback :)

**Comment by LosTigeros** [comment]
> This method will remove the requirement of adding every command to the plugin.yml file.

https://github.com/Mas281/Network-depr/blob/master/Server/src/main/java/me/itsmas/network/server/user/command/UserCommands.java

**Comment by IceMeltt** [comment]
@LosTigeros hmm, that looks interesting.

Waiting for other opinions about this command system.
