### ISSUE TITLE
Remove of waiting for the server to start

### ISSUE THREAD

**Issue by kacperduras** [meleride/Paper#5]
* **I'm submitting a ...**
  - [x] feature request

* **What is the current behavior?**

The server starts after 15 seconds.

* **If the issue isn't a support request, what is the expected behavior?**

I want to speed up launching the server, without any anoyed messages.

* **If the issue is a feature request, what is the motivation for add the behavior?**

Convenience.

**Comment by IceMeltt** [comment]
Yeah, waiting 15 seconds for the end of the announce isn't a nice thing.

I'm suggesting to decrease wait time to only 3 seconds, when the server will find any update.
