### ISSUE TITLE
Automatically incrementing / decrementing server's assigned memory when it is / isn't needed

### ISSUE THREAD

**Issue by IceMeltt** [meleride/Paper#9]
* **I'm submitting a ...**
  - [x] feature request

* **What is the current behavior?**
The server is using the assigned memory in the batch file as it's maximum memory. 
We can decrease, or increase the value of the server's maximum memory when the server doesn't / does need so much memory. 
Imagine, when it is 03:00AM and you have only 2 players on the server.
Server don't need more memory than ~1.5-2 gigabytes of RAM.
So why we must have at this moment still 6GB of RAM as the maximum memory?

* **If the issue isn't a support request, what is the expected behavior?**
Server can automatically set the assigned maximum memory's value when it isn't using more than the requiring memory.

* **If the issue is a feature request, what is the motivation for add the behavior?**
Automation, and limitting the maximum memory when it isn't needed as the big value.

**Comment by kacperduras** [comment]
I don't understand your idea, why? Because it's bullshit. JVM has a memory manager, why should we manage it ourselves? A lot of work, little benefits.

**Comment by IceMeltt** [comment]
Well, I thought that we can save some memory by introducing this idea. But, if it's really hard to do, we can reject this idea :stuck_out_tongue:

**Comment by kacperduras** [comment]
@IceMeltt Did you read my feedback about it?
```
VM has GC and a lot of other solutions for memory managing, why should we manage it ourselves?
```

**Comment by IceMeltt** [comment]
Yup, i read it, and I know that stuff like GC actually exists in Java - because of this, I admitted this idea as a stupid thing.
